# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c4a219ba81362dd4d57fa497bc6387447a8ffcb28562998d60b5864184bbbae9977db5ed8e5dddea8de27074d63770cc06ed47438ec15be684739e7e7fc0d48

test:
  secret_key_base: 93cddb9bf6d77276252e3a898514ce98610e370898d73da5aa17d8b685e12f1ea45ff6b9a7b8113e3cdd06dd04148f908a097658a3483104564545e882370a88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
